import { MigrationInterface, QueryRunner } from "typeorm";

export class RenameJobToTask1772614023201 implements MigrationInterface {
    name = 'RenameJobToTask1772614023201'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_session_unsent" ("sessionId" varchar PRIMARY KEY NOT NULL, "input" text, "provider" varchar, "fastMode" boolean, "selection" text, "uploadId" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_session_unsent"("sessionId", "input", "provider", "fastMode", "selection", "uploadId") SELECT "sessionId", "input", "provider", "fastMode", "selection", "uploadId" FROM "session_unsent"`);
        await queryRunner.query(`DROP TABLE "session_unsent"`);
        await queryRunner.query(`ALTER TABLE "temporary_session_unsent" RENAME TO "session_unsent"`);
        // await queryRunner.query(`DROP INDEX "IDX_SESSION_TURN_SESSION_ID"`);
        await queryRunner.query(`CREATE TABLE "temporary_session_turn" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "sessionId" varchar NOT NULL, "turn" integer NOT NULL, "beginTime" datetime NOT NULL, "endTime" datetime, "request" text NOT NULL, "response" text NOT NULL, "provider" varchar NOT NULL, "fastMode" boolean NOT NULL, "selection" text, "uploadId" integer, "version" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_session_turn"("id", "sessionId", "turn", "beginTime", "endTime", "request", "response", "provider", "fastMode", "selection", "uploadId", "version") SELECT "id", "sessionId", "turn", "beginTime", "endTime", "request", "response", "provider", "fastMode", "selection", "uploadId", "version" FROM "session_turn"`);
        await queryRunner.query(`DROP TABLE "session_turn"`);
        await queryRunner.query(`ALTER TABLE "temporary_session_turn" RENAME TO "session_turn"`);
        await queryRunner.query(`CREATE INDEX "IDX_SESSION_TURN_SESSION_ID" ON "session_turn" ("sessionId") `);
        // await queryRunner.query(`DROP INDEX "IDX_SESSION_CONTEXT_SESSION_ID"`);
        await queryRunner.query(`CREATE TABLE "temporary_session_context" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "sessionId" varchar NOT NULL, "role" varchar NOT NULL, "content" text NOT NULL, "selection" text, "uploadId" integer, "version" integer NOT NULL, "turn" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`INSERT INTO "temporary_session_context"("id", "sessionId", "role", "content", "selection", "uploadId", "version", "turn", "createdAt") SELECT "id", "sessionId", "role", "content", "selection", "uploadId", "version", "turn", "createdAt" FROM "session_context"`);
        await queryRunner.query(`DROP TABLE "session_context"`);
        await queryRunner.query(`ALTER TABLE "temporary_session_context" RENAME TO "session_context"`);
        await queryRunner.query(`CREATE INDEX "IDX_SESSION_CONTEXT_SESSION_ID" ON "session_context" ("sessionId") `);
        await queryRunner.query(`CREATE TABLE "temporary_session" ("sessionId" varchar PRIMARY KEY NOT NULL, "projectId" varchar NOT NULL, "group" integer NOT NULL, "currentVersion" integer NOT NULL, "lastTurn" integer, "provider" varchar NOT NULL, "status" varchar NOT NULL, "fastMode" boolean NOT NULL, "subject" varchar, "summary" text, "summaryTurn" integer, "errorMessage" text, "updatedAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`INSERT INTO "temporary_session"("sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt") SELECT "sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt" FROM "session"`);
        await queryRunner.query(`DROP TABLE "session"`);
        await queryRunner.query(`ALTER TABLE "temporary_session" RENAME TO "session"`);
        // await queryRunner.query(`DROP INDEX "IDX_SESSION_UPLOAD_SESSION_ID"`);
        // await queryRunner.query(`DROP INDEX "IDX_SESSION_TURN_SESSION_ID"`);
        // await queryRunner.query(`DROP INDEX "IDX_SESSION_CONTEXT_SESSION_ID"`);
        await queryRunner.query(`CREATE TABLE "temporary_session_unsent" ("sessionId" varchar PRIMARY KEY NOT NULL, "input" text, "provider" varchar, "fastMode" boolean, "selection" text, "uploadId" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_session_unsent"("sessionId", "input", "provider", "fastMode", "selection", "uploadId") SELECT "sessionId", "input", "provider", "fastMode", "selection", "uploadId" FROM "session_unsent"`);
        await queryRunner.query(`DROP TABLE "session_unsent"`);
        await queryRunner.query(`ALTER TABLE "temporary_session_unsent" RENAME TO "session_unsent"`);
        await queryRunner.query(`CREATE TABLE "temporary_project" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "accountId" integer, "rulesAndGoal" text NOT NULL, "imageGenerationPref" varchar, "defaultProvider" text, "modelRole" varchar, "sessionIds" text NOT NULL DEFAULT ('[]'), "lastAssignedSessionGroup" integer, "activeSessionId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" varchar NOT NULL DEFAULT ('ready'), "taskId" varchar)`);
        await queryRunner.query(`INSERT INTO "temporary_project"("id", "name", "accountId", "rulesAndGoal", "imageGenerationPref", "defaultProvider", "modelRole", "sessionIds", "lastAssignedSessionGroup", "activeSessionId", "createdAt", "updatedAt", "status", "taskId") SELECT "id", "name", "accountId", "rulesAndGoal", "imageGenerationPref", "defaultProvider", "modelRole", "sessionIds", "lastAssignedSessionGroup", "activeSessionId", "createdAt", "updatedAt", "status", "jobId" FROM "project"`);
        await queryRunner.query(`DROP TABLE "project"`);
        await queryRunner.query(`ALTER TABLE "temporary_project" RENAME TO "project"`);
        await queryRunner.query(`CREATE TABLE "temporary_session" ("sessionId" varchar PRIMARY KEY NOT NULL, "projectId" varchar NOT NULL, "group" integer NOT NULL, "currentVersion" integer NOT NULL, "lastTurn" integer, "provider" varchar NOT NULL, "status" varchar NOT NULL, "fastMode" boolean NOT NULL, "subject" varchar, "summary" text, "summaryTurn" integer, "errorMessage" text, "updatedAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`INSERT INTO "temporary_session"("sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt") SELECT "sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt" FROM "session"`);
        await queryRunner.query(`DROP TABLE "session"`);
        await queryRunner.query(`ALTER TABLE "temporary_session" RENAME TO "session"`);
        await queryRunner.query(`CREATE TABLE "task" ("id" varchar PRIMARY KEY NOT NULL, "status" varchar NOT NULL DEFAULT ('pending'), "errorMessage" text, "steps" text NOT NULL DEFAULT ('[]'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "temporary_session_upload" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "sessionId" varchar NOT NULL, "filename" varchar NOT NULL, "originalName" varchar NOT NULL, "mimeType" varchar NOT NULL, "size" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "temporary_session_upload"("id", "sessionId", "filename", "originalName", "mimeType", "size", "createdAt") SELECT "id", "sessionId", "filename", "originalName", "mimeType", "size", "createdAt" FROM "session_upload"`);
        await queryRunner.query(`DROP TABLE "session_upload"`);
        await queryRunner.query(`ALTER TABLE "temporary_session_upload" RENAME TO "session_upload"`);
        await queryRunner.query(`CREATE TABLE "temporary_session_unsent" ("sessionId" varchar PRIMARY KEY NOT NULL, "input" text, "provider" varchar, "fastMode" boolean, "selection" text, "uploadId" integer, CONSTRAINT "UQ_803e7533876c4fd2daf538982e5" UNIQUE ("uploadId"))`);
        await queryRunner.query(`INSERT INTO "temporary_session_unsent"("sessionId", "input", "provider", "fastMode", "selection", "uploadId") SELECT "sessionId", "input", "provider", "fastMode", "selection", "uploadId" FROM "session_unsent"`);
        await queryRunner.query(`DROP TABLE "session_unsent"`);
        await queryRunner.query(`ALTER TABLE "temporary_session_unsent" RENAME TO "session_unsent"`);
        await queryRunner.query(`CREATE TABLE "temporary_session_context" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "sessionId" varchar NOT NULL, "role" varchar NOT NULL, "content" text NOT NULL, "selection" text, "uploadId" integer, "version" integer NOT NULL, "turn" integer NOT NULL, "createdAt" datetime NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_session_context"("id", "sessionId", "role", "content", "selection", "uploadId", "version", "turn", "createdAt") SELECT "id", "sessionId", "role", "content", "selection", "uploadId", "version", "turn", "createdAt" FROM "session_context"`);
        await queryRunner.query(`DROP TABLE "session_context"`);
        await queryRunner.query(`ALTER TABLE "temporary_session_context" RENAME TO "session_context"`);
        await queryRunner.query(`CREATE TABLE "temporary_project" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "accountId" integer, "rulesAndGoal" text NOT NULL, "imageGenerationPref" varchar, "defaultProvider" text, "modelRole" varchar, "sessionIds" text NOT NULL DEFAULT ('[]'), "lastAssignedSessionGroup" integer, "activeSessionId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" varchar NOT NULL DEFAULT ('ready'), "taskId" varchar)`);
        await queryRunner.query(`INSERT INTO "temporary_project"("id", "name", "accountId", "rulesAndGoal", "imageGenerationPref", "defaultProvider", "modelRole", "sessionIds", "lastAssignedSessionGroup", "activeSessionId", "createdAt", "updatedAt", "status", "taskId") SELECT "id", "name", "accountId", "rulesAndGoal", "imageGenerationPref", "defaultProvider", "modelRole", "sessionIds", "lastAssignedSessionGroup", "activeSessionId", "createdAt", "updatedAt", "status", "taskId" FROM "project"`);
        await queryRunner.query(`DROP TABLE "project"`);
        await queryRunner.query(`ALTER TABLE "temporary_project" RENAME TO "project"`);
        await queryRunner.query(`CREATE TABLE "temporary_session" ("sessionId" varchar PRIMARY KEY NOT NULL, "projectId" varchar NOT NULL, "group" integer NOT NULL, "currentVersion" integer NOT NULL, "lastTurn" integer, "provider" varchar NOT NULL, "status" varchar NOT NULL, "fastMode" boolean NOT NULL, "subject" text, "summary" text, "summaryTurn" integer, "errorMessage" text, "updatedAt" datetime NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_session"("sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt") SELECT "sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt" FROM "session"`);
        await queryRunner.query(`DROP TABLE "session"`);
        await queryRunner.query(`ALTER TABLE "temporary_session" RENAME TO "session"`);
        await queryRunner.query(`CREATE INDEX "IDX_35e857e65be1ed2d9a3224e522" ON "session_upload" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_99c4d32c355c821e532350caf9" ON "session_turn" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb44d1f6b20bef83d789e54cb3" ON "session_context" ("sessionId") `);
        await queryRunner.query(`CREATE TABLE "temporary_session_unsent" ("sessionId" varchar PRIMARY KEY NOT NULL, "input" text, "provider" varchar, "fastMode" boolean, "selection" text, "uploadId" integer, CONSTRAINT "UQ_803e7533876c4fd2daf538982e5" UNIQUE ("uploadId"), CONSTRAINT "FK_70a6f30d6699d9620ce2e0539f0" FOREIGN KEY ("uploadId") REFERENCES "session_upload" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_session_unsent"("sessionId", "input", "provider", "fastMode", "selection", "uploadId") SELECT "sessionId", "input", "provider", "fastMode", "selection", "uploadId" FROM "session_unsent"`);
        await queryRunner.query(`DROP TABLE "session_unsent"`);
        await queryRunner.query(`ALTER TABLE "temporary_session_unsent" RENAME TO "session_unsent"`);
        // await queryRunner.query(`DROP INDEX "IDX_99c4d32c355c821e532350caf9"`);
        await queryRunner.query(`CREATE TABLE "temporary_session_turn" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "sessionId" varchar NOT NULL, "turn" integer NOT NULL, "beginTime" datetime NOT NULL, "endTime" datetime, "request" text NOT NULL, "response" text NOT NULL, "provider" varchar NOT NULL, "fastMode" boolean NOT NULL, "selection" text, "uploadId" integer, "version" integer NOT NULL, CONSTRAINT "FK_4f6edc5c023b185dc954fe930a2" FOREIGN KEY ("uploadId") REFERENCES "session_upload" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_session_turn"("id", "sessionId", "turn", "beginTime", "endTime", "request", "response", "provider", "fastMode", "selection", "uploadId", "version") SELECT "id", "sessionId", "turn", "beginTime", "endTime", "request", "response", "provider", "fastMode", "selection", "uploadId", "version" FROM "session_turn"`);
        await queryRunner.query(`DROP TABLE "session_turn"`);
        await queryRunner.query(`ALTER TABLE "temporary_session_turn" RENAME TO "session_turn"`);
        await queryRunner.query(`CREATE INDEX "IDX_99c4d32c355c821e532350caf9" ON "session_turn" ("sessionId") `);
        // await queryRunner.query(`DROP INDEX "IDX_fb44d1f6b20bef83d789e54cb3"`);
        await queryRunner.query(`CREATE TABLE "temporary_session_context" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "sessionId" varchar NOT NULL, "role" varchar NOT NULL, "content" text NOT NULL, "selection" text, "uploadId" integer, "version" integer NOT NULL, "turn" integer NOT NULL, "createdAt" datetime NOT NULL, CONSTRAINT "FK_d2ed909b0d1f3355b767caf0e5e" FOREIGN KEY ("uploadId") REFERENCES "session_upload" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_session_context"("id", "sessionId", "role", "content", "selection", "uploadId", "version", "turn", "createdAt") SELECT "id", "sessionId", "role", "content", "selection", "uploadId", "version", "turn", "createdAt" FROM "session_context"`);
        await queryRunner.query(`DROP TABLE "session_context"`);
        await queryRunner.query(`ALTER TABLE "temporary_session_context" RENAME TO "session_context"`);
        await queryRunner.query(`CREATE INDEX "IDX_fb44d1f6b20bef83d789e54cb3" ON "session_context" ("sessionId") `);
        await queryRunner.query(`CREATE TABLE "temporary_session" ("sessionId" varchar PRIMARY KEY NOT NULL, "projectId" varchar NOT NULL, "group" integer NOT NULL, "currentVersion" integer NOT NULL, "lastTurn" integer, "provider" varchar NOT NULL, "status" varchar NOT NULL, "fastMode" boolean NOT NULL, "subject" text, "summary" text, "summaryTurn" integer, "errorMessage" text, "updatedAt" datetime NOT NULL, CONSTRAINT "FK_5d6cdc979e4cf4e067943fedd8f" FOREIGN KEY ("projectId") REFERENCES "project" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_session"("sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt") SELECT "sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt" FROM "session"`);
        await queryRunner.query(`DROP TABLE "session"`);
        await queryRunner.query(`ALTER TABLE "temporary_session" RENAME TO "session"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "session" RENAME TO "temporary_session"`);
        await queryRunner.query(`CREATE TABLE "session" ("sessionId" varchar PRIMARY KEY NOT NULL, "projectId" varchar NOT NULL, "group" integer NOT NULL, "currentVersion" integer NOT NULL, "lastTurn" integer, "provider" varchar NOT NULL, "status" varchar NOT NULL, "fastMode" boolean NOT NULL, "subject" text, "summary" text, "summaryTurn" integer, "errorMessage" text, "updatedAt" datetime NOT NULL)`);
        await queryRunner.query(`INSERT INTO "session"("sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt") SELECT "sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt" FROM "temporary_session"`);
        await queryRunner.query(`DROP TABLE "temporary_session"`);
        await queryRunner.query(`DROP INDEX "IDX_fb44d1f6b20bef83d789e54cb3"`);
        await queryRunner.query(`ALTER TABLE "session_context" RENAME TO "temporary_session_context"`);
        await queryRunner.query(`CREATE TABLE "session_context" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "sessionId" varchar NOT NULL, "role" varchar NOT NULL, "content" text NOT NULL, "selection" text, "uploadId" integer, "version" integer NOT NULL, "turn" integer NOT NULL, "createdAt" datetime NOT NULL)`);
        await queryRunner.query(`INSERT INTO "session_context"("id", "sessionId", "role", "content", "selection", "uploadId", "version", "turn", "createdAt") SELECT "id", "sessionId", "role", "content", "selection", "uploadId", "version", "turn", "createdAt" FROM "temporary_session_context"`);
        await queryRunner.query(`DROP TABLE "temporary_session_context"`);
        await queryRunner.query(`CREATE INDEX "IDX_fb44d1f6b20bef83d789e54cb3" ON "session_context" ("sessionId") `);
        await queryRunner.query(`DROP INDEX "IDX_99c4d32c355c821e532350caf9"`);
        await queryRunner.query(`ALTER TABLE "session_turn" RENAME TO "temporary_session_turn"`);
        await queryRunner.query(`CREATE TABLE "session_turn" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "sessionId" varchar NOT NULL, "turn" integer NOT NULL, "beginTime" datetime NOT NULL, "endTime" datetime, "request" text NOT NULL, "response" text NOT NULL, "provider" varchar NOT NULL, "fastMode" boolean NOT NULL, "selection" text, "uploadId" integer, "version" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "session_turn"("id", "sessionId", "turn", "beginTime", "endTime", "request", "response", "provider", "fastMode", "selection", "uploadId", "version") SELECT "id", "sessionId", "turn", "beginTime", "endTime", "request", "response", "provider", "fastMode", "selection", "uploadId", "version" FROM "temporary_session_turn"`);
        await queryRunner.query(`DROP TABLE "temporary_session_turn"`);
        await queryRunner.query(`CREATE INDEX "IDX_99c4d32c355c821e532350caf9" ON "session_turn" ("sessionId") `);
        await queryRunner.query(`ALTER TABLE "session_unsent" RENAME TO "temporary_session_unsent"`);
        await queryRunner.query(`CREATE TABLE "session_unsent" ("sessionId" varchar PRIMARY KEY NOT NULL, "input" text, "provider" varchar, "fastMode" boolean, "selection" text, "uploadId" integer, CONSTRAINT "UQ_803e7533876c4fd2daf538982e5" UNIQUE ("uploadId"))`);
        await queryRunner.query(`INSERT INTO "session_unsent"("sessionId", "input", "provider", "fastMode", "selection", "uploadId") SELECT "sessionId", "input", "provider", "fastMode", "selection", "uploadId" FROM "temporary_session_unsent"`);
        await queryRunner.query(`DROP TABLE "temporary_session_unsent"`);
        await queryRunner.query(`DROP INDEX "IDX_fb44d1f6b20bef83d789e54cb3"`);
        await queryRunner.query(`DROP INDEX "IDX_99c4d32c355c821e532350caf9"`);
        await queryRunner.query(`DROP INDEX "IDX_35e857e65be1ed2d9a3224e522"`);
        await queryRunner.query(`ALTER TABLE "session" RENAME TO "temporary_session"`);
        await queryRunner.query(`CREATE TABLE "session" ("sessionId" varchar PRIMARY KEY NOT NULL, "projectId" varchar NOT NULL, "group" integer NOT NULL, "currentVersion" integer NOT NULL, "lastTurn" integer, "provider" varchar NOT NULL, "status" varchar NOT NULL, "fastMode" boolean NOT NULL, "subject" varchar, "summary" text, "summaryTurn" integer, "errorMessage" text, "updatedAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`INSERT INTO "session"("sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt") SELECT "sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt" FROM "temporary_session"`);
        await queryRunner.query(`DROP TABLE "temporary_session"`);
        await queryRunner.query(`ALTER TABLE "project" RENAME TO "temporary_project"`);
        await queryRunner.query(`CREATE TABLE "project" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "accountId" integer, "rulesAndGoal" text NOT NULL, "imageGenerationPref" varchar, "defaultProvider" text, "modelRole" varchar, "sessionIds" text NOT NULL DEFAULT ('[]'), "lastAssignedSessionGroup" integer, "activeSessionId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" varchar NOT NULL DEFAULT ('ready'), "taskId" varchar)`);
        await queryRunner.query(`INSERT INTO "project"("id", "name", "accountId", "rulesAndGoal", "imageGenerationPref", "defaultProvider", "modelRole", "sessionIds", "lastAssignedSessionGroup", "activeSessionId", "createdAt", "updatedAt", "status", "taskId") SELECT "id", "name", "accountId", "rulesAndGoal", "imageGenerationPref", "defaultProvider", "modelRole", "sessionIds", "lastAssignedSessionGroup", "activeSessionId", "createdAt", "updatedAt", "status", "taskId" FROM "temporary_project"`);
        await queryRunner.query(`DROP TABLE "temporary_project"`);
        await queryRunner.query(`ALTER TABLE "session_context" RENAME TO "temporary_session_context"`);
        await queryRunner.query(`CREATE TABLE "session_context" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "sessionId" varchar NOT NULL, "role" varchar NOT NULL, "content" text NOT NULL, "selection" text, "uploadId" integer, "version" integer NOT NULL, "turn" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`INSERT INTO "session_context"("id", "sessionId", "role", "content", "selection", "uploadId", "version", "turn", "createdAt") SELECT "id", "sessionId", "role", "content", "selection", "uploadId", "version", "turn", "createdAt" FROM "temporary_session_context"`);
        await queryRunner.query(`DROP TABLE "temporary_session_context"`);
        await queryRunner.query(`ALTER TABLE "session_unsent" RENAME TO "temporary_session_unsent"`);
        await queryRunner.query(`CREATE TABLE "session_unsent" ("sessionId" varchar PRIMARY KEY NOT NULL, "input" text, "provider" varchar, "fastMode" boolean, "selection" text, "uploadId" integer)`);
        await queryRunner.query(`INSERT INTO "session_unsent"("sessionId", "input", "provider", "fastMode", "selection", "uploadId") SELECT "sessionId", "input", "provider", "fastMode", "selection", "uploadId" FROM "temporary_session_unsent"`);
        await queryRunner.query(`DROP TABLE "temporary_session_unsent"`);
        await queryRunner.query(`ALTER TABLE "session_upload" RENAME TO "temporary_session_upload"`);
        await queryRunner.query(`CREATE TABLE "session_upload" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "sessionId" varchar NOT NULL, "filename" varchar NOT NULL, "originalName" varchar NOT NULL, "mimeType" varchar NOT NULL, "size" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`INSERT INTO "session_upload"("id", "sessionId", "filename", "originalName", "mimeType", "size", "createdAt") SELECT "id", "sessionId", "filename", "originalName", "mimeType", "size", "createdAt" FROM "temporary_session_upload"`);
        await queryRunner.query(`DROP TABLE "temporary_session_upload"`);
        await queryRunner.query(`DROP TABLE "task"`);
        await queryRunner.query(`ALTER TABLE "session" RENAME TO "temporary_session"`);
        await queryRunner.query(`CREATE TABLE "session" ("sessionId" varchar PRIMARY KEY NOT NULL, "projectId" varchar NOT NULL, "group" integer NOT NULL, "currentVersion" integer NOT NULL, "lastTurn" integer, "provider" varchar NOT NULL, "status" varchar NOT NULL, "fastMode" boolean NOT NULL, "subject" varchar, "summary" text, "summaryTurn" integer, "errorMessage" text, "updatedAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`INSERT INTO "session"("sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt") SELECT "sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt" FROM "temporary_session"`);
        await queryRunner.query(`DROP TABLE "temporary_session"`);
        await queryRunner.query(`ALTER TABLE "project" RENAME TO "temporary_project"`);
        await queryRunner.query(`CREATE TABLE "project" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "accountId" integer, "rulesAndGoal" text NOT NULL, "imageGenerationPref" varchar, "defaultProvider" text, "modelRole" varchar, "sessionIds" text NOT NULL DEFAULT ('[]'), "lastAssignedSessionGroup" integer, "activeSessionId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" varchar NOT NULL DEFAULT ('ready'), "jobId" varchar)`);
        await queryRunner.query(`INSERT INTO "project"("id", "name", "accountId", "rulesAndGoal", "imageGenerationPref", "defaultProvider", "modelRole", "sessionIds", "lastAssignedSessionGroup", "activeSessionId", "createdAt", "updatedAt", "status", "jobId") SELECT "id", "name", "accountId", "rulesAndGoal", "imageGenerationPref", "defaultProvider", "modelRole", "sessionIds", "lastAssignedSessionGroup", "activeSessionId", "createdAt", "updatedAt", "status", "taskId" FROM "temporary_project"`);
        await queryRunner.query(`DROP TABLE "temporary_project"`);
        await queryRunner.query(`ALTER TABLE "session_unsent" RENAME TO "temporary_session_unsent"`);
        await queryRunner.query(`CREATE TABLE "session_unsent" ("sessionId" varchar PRIMARY KEY NOT NULL, "input" text, "provider" varchar, "fastMode" boolean, "selection" text, "uploadId" integer)`);
        await queryRunner.query(`INSERT INTO "session_unsent"("sessionId", "input", "provider", "fastMode", "selection", "uploadId") SELECT "sessionId", "input", "provider", "fastMode", "selection", "uploadId" FROM "temporary_session_unsent"`);
        await queryRunner.query(`DROP TABLE "temporary_session_unsent"`);
        await queryRunner.query(`CREATE INDEX "IDX_SESSION_CONTEXT_SESSION_ID" ON "session_context" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_SESSION_TURN_SESSION_ID" ON "session_turn" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_SESSION_UPLOAD_SESSION_ID" ON "session_upload" ("sessionId") `);
        await queryRunner.query(`ALTER TABLE "session" RENAME TO "temporary_session"`);
        await queryRunner.query(`CREATE TABLE "session" ("sessionId" varchar PRIMARY KEY NOT NULL, "projectId" varchar NOT NULL, "group" integer NOT NULL, "currentVersion" integer NOT NULL, "lastTurn" integer, "provider" varchar NOT NULL, "status" varchar NOT NULL, "fastMode" boolean NOT NULL, "subject" varchar, "summary" text, "summaryTurn" integer, "errorMessage" text, "updatedAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), CONSTRAINT "FK_5d6cdc979e4cf4e067943fedd8f" FOREIGN KEY ("projectId") REFERENCES "project" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "session"("sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt") SELECT "sessionId", "projectId", "group", "currentVersion", "lastTurn", "provider", "status", "fastMode", "subject", "summary", "summaryTurn", "errorMessage", "updatedAt" FROM "temporary_session"`);
        await queryRunner.query(`DROP TABLE "temporary_session"`);
        // await queryRunner.query(`DROP INDEX "IDX_SESSION_CONTEXT_SESSION_ID"`);
        await queryRunner.query(`ALTER TABLE "session_context" RENAME TO "temporary_session_context"`);
        await queryRunner.query(`CREATE TABLE "session_context" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "sessionId" varchar NOT NULL, "role" varchar NOT NULL, "content" text NOT NULL, "selection" text, "uploadId" integer, "version" integer NOT NULL, "turn" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), CONSTRAINT "FK_d2ed909b0d1f3355b767caf0e5e" FOREIGN KEY ("uploadId") REFERENCES "session_upload" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_fb44d1f6b20bef83d789e54cb37" FOREIGN KEY ("sessionId") REFERENCES "session" ("sessionId") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "session_context"("id", "sessionId", "role", "content", "selection", "uploadId", "version", "turn", "createdAt") SELECT "id", "sessionId", "role", "content", "selection", "uploadId", "version", "turn", "createdAt" FROM "temporary_session_context"`);
        await queryRunner.query(`DROP TABLE "temporary_session_context"`);
        await queryRunner.query(`CREATE INDEX "IDX_SESSION_CONTEXT_SESSION_ID" ON "session_context" ("sessionId") `);
        // await queryRunner.query(`DROP INDEX "IDX_SESSION_TURN_SESSION_ID"`);
        await queryRunner.query(`ALTER TABLE "session_turn" RENAME TO "temporary_session_turn"`);
        await queryRunner.query(`CREATE TABLE "session_turn" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "sessionId" varchar NOT NULL, "turn" integer NOT NULL, "beginTime" datetime NOT NULL, "endTime" datetime, "request" text NOT NULL, "response" text NOT NULL, "provider" varchar NOT NULL, "fastMode" boolean NOT NULL, "selection" text, "uploadId" integer, "version" integer NOT NULL, CONSTRAINT "FK_4f6edc5c023b185dc954fe930a2" FOREIGN KEY ("uploadId") REFERENCES "session_upload" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_99c4d32c355c821e532350caf98" FOREIGN KEY ("sessionId") REFERENCES "session" ("sessionId") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "session_turn"("id", "sessionId", "turn", "beginTime", "endTime", "request", "response", "provider", "fastMode", "selection", "uploadId", "version") SELECT "id", "sessionId", "turn", "beginTime", "endTime", "request", "response", "provider", "fastMode", "selection", "uploadId", "version" FROM "temporary_session_turn"`);
        await queryRunner.query(`DROP TABLE "temporary_session_turn"`);
        await queryRunner.query(`CREATE INDEX "IDX_SESSION_TURN_SESSION_ID" ON "session_turn" ("sessionId") `);
        await queryRunner.query(`ALTER TABLE "session_unsent" RENAME TO "temporary_session_unsent"`);
        await queryRunner.query(`CREATE TABLE "session_unsent" ("sessionId" varchar PRIMARY KEY NOT NULL, "input" text, "provider" varchar, "fastMode" boolean, "selection" text, "uploadId" integer, CONSTRAINT "FK_70a6f30d6699d9620ce2e0539f0" FOREIGN KEY ("uploadId") REFERENCES "session_upload" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "session_unsent"("sessionId", "input", "provider", "fastMode", "selection", "uploadId") SELECT "sessionId", "input", "provider", "fastMode", "selection", "uploadId" FROM "temporary_session_unsent"`);
        await queryRunner.query(`DROP TABLE "temporary_session_unsent"`);
    }

}
