services:
  app:
    build:
      context: .
      args:
        APP_BASE_PATH: "${APP_BASE_PATH}"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./server/data:${DATA_DIR}"
    restart: always
    env_file:
      - .env

  screenshot:
    build:
      context: ./screenshot-service
    ports:
      - "3001:3001"
    shm_size: '1gb'
    volumes:
      - "./server/data:/app/shared:ro"
    restart: always
