model_list:
  - model_name: gemini-2.5-flash-image
    litellm_params:
      model: gemini/gemini-2.5-flash-image

  - model_name: gpt-5.1-codex
    litellm_params:
      model: openai/gpt-5.1-codex

  - model_name: gemini-3-pro-preview
    litellm_params:
      model: gemini/gemini-3-pro-preview