services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/test_sse_sessions:cached
    env_file:
      - .env
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000"
    command: --config /app/config.yaml
    volumes:
      - ../litellm/config.yaml:/app/config.yaml
    env_file:
      - .env
    restart: unless-stopped

  screenshot:
    build:
      context: ../screenshot-service
    command: node --watch index.js
    ports:
      - "3001:3001"
    shm_size: '1gb'
    volumes:
      - "../server/data:/app/shared:ro"
      - "../screenshot-service/index.js:/app/index.js"
    restart: always
